'use client';
import { AuthProvider } from '@/contexts/authContext/authContext';
import { ReactQueryClientProvider } from '@/services/queryClient';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { usePathname } from 'next/navigation';

import PrivateRoute from '@/components/privateRoute/privateRoute.component';
import { checkIsPublicRoute } from '@/functions';
import { NotiStackProvider } from '@/services/notistackProvider';
import theme from '../../theme/theme';
import './globals.css';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isPublicPage = checkIsPublicRoute(pathname.replace('/', ''));
  console.log(pathname.replace('/', ''));
  console.log(isPublicPage);
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>
          <NotiStackProvider>
            <ThemeProvider theme={theme}>
              <AuthProvider>
                <AppRouterCacheProvider>
                  {isPublicPage && children}
                  {!isPublicPage && <PrivateRoute>{children}</PrivateRoute>}
                </AppRouterCacheProvider>
              </AuthProvider>
            </ThemeProvider>
          </NotiStackProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
